# Nasdaq-100 Constituents (Auto-Updated)
# Updated: 2026-09-14 23:34:47
# Source: Nasdaq API + Schwab Official Top 20 + Estimates
#
STOCKS = [
    ("NVDA", "NVIDIA Corporation", "Technology", 8.63),
    ("AAPL", "Apple Inc.", "Technology", 7.38),
    ("MSFT", "Microsoft Corporation", "Technology", 5.82),
    ("MU", "Micron Technology, Inc.", "Technology", 5.10),
    ("AMZN", "Amazon.com, Inc.", "Consumer Discretionary", 4.33),
    ("AMD", "Advanced Micro Devices, Inc.", "Technology", 3.74),
    ("META", "Meta Platforms, Inc. Class A", "Communication Services", 3.08),
    ("GOOGL", "Alphabet Inc. Class A", "Communication Services", 3.07),
    ("TSLA", "Tesla, Inc.", "Consumer Discretionary", 2.93),
    ("GOOG", "Alphabet Inc. Class C", "Communication Services", 2.85),
    ("AVGO", "Broadcom Inc.", "Technology", 2.75),
    ("INTC", "Intel Corporation", "Technology", 2.35),
    ("WMT", "Walmart Inc.", "Consumer Staples", 2.27),
    ("CSCO", "Cisco Systems, Inc. Common Stock (DE)", "Technology", 1.90),
    ("COST", "Costco Wholesale Corporation", "Consumer Staples", 1.76),
    ("LRCX", "Lam Research Corporation", "Technology", 1.74),
    ("PLTR", "Palantir Technologies Inc. Class A", "Technology", 1.71),
    ("AMAT", "Applied Materials, Inc.", "Technology", 1.64),
    ("NFLX", "Netflix, Inc.", "Communication Services", 1.41),
    ("SPCX", "Space Exploration Technologies Corp. Class A", "Industrials", 1.24),
    ("SHOP", "Shopify Inc. Class A Subordinate Voting Shares", "Consumer Discretionary", 1.11),
    ("QCOM", "QUALCOMM Incorporated", "Technology", 1.01),
    ("TXN", "Texas Instruments Incorporated", "Technology", 0.92),
    ("ASML", "ASML Holding N.V. New York Registry Shares", "Technology", 0.89),
    ("ADBE", "Adobe Inc.", "Technology", 0.87),
    ("KLAC", "KLA Corporation", "Technology", 0.85),
    ("INTU", "Intuit Inc.", "Technology", 0.82),
    ("APP", "Applovin Corporation Class A", "Technology", 0.79),
    ("ARM", "Arm Holdings plc American Depositary Shares", "Technology", 0.75),
    ("SBUX", "Starbucks Corporation", "Consumer Discretionary", 0.72),
    ("PDD", "PDD Holdings Inc. American Depositary Shares", "Consumer Discretionary", 0.70),
    ("ABNB", "Airbnb, Inc. Class A", "Consumer Discretionary", 0.68),
    ("ADP", "Automatic Data Processing, Inc.", "Technology", 0.66),
    ("CEG", "Constellation Energy Corporation", "Utilities", 0.63),
    ("SNDK", "Sandisk Corporation", "Technology", 0.63),
    ("DASH", "DoorDash, Inc. Class A", "Consumer Discretionary", 0.60),
    ("LIN", "Linde plc Ordinary Shares", "Industrials", 0.60),
    ("MELI", "MercadoLibre, Inc.", "Consumer Discretionary", 0.58),
    ("CRWD", "CrowdStrike Holdings, Inc. Class A", "Technology", 0.58),
    ("AMGN", "Amgen Inc.", "Health Care", 0.56),
    ("MAR", "Marriott International Class A", "Consumer Discretionary", 0.56),
    ("STX", "Seagate Technology Holdings PLC Ordinary Shares (Ireland)", "Technology", 0.56),
    ("CSX", "CSX Corporation", "Industrials", 0.54),
    ("CMCSA", "Comcast Corporation Class A", "Communication Services", 0.53),
    ("MRVL", "Marvell Technology, Inc.", "Technology", 0.53),
    ("TMUS", "T-Mobile US, Inc.", "Communication Services", 0.52),
    ("DDOG", "Datadog, Inc. Class A", "Technology", 0.51),
    ("MNST", "Monster Beverage", "Consumer Staples", 0.50),
    ("PEP", "PepsiCo, Inc.", "Consumer Staples", 0.50),
    ("ADI", "Analog Devices, Inc.", "Technology", 0.48),
    ("CDNS", "Cadence Design Systems, Inc.", "Technology", 0.48),
    ("REGN", "Regeneron Pharmaceuticals, Inc.", "Health Care", 0.46),
    ("WDC", "Western Digital Corporation", "Technology", 0.46),
    ("LITE", "Lumentum Holdings Inc.", "Technology", 0.45),
    ("MDLZ", "Mondelez International, Inc. Class A", "Consumer Staples", 0.44),
    ("CTAS", "Cintas Corporation", "Industrials", 0.43),
    ("GILD", "Gilead Sciences, Inc.", "Health Care", 0.43),
    ("SNPS", "Synopsys, Inc.", "Technology", 0.43),
    ("ROST", "Ross Stores, Inc.", "Consumer Discretionary", 0.42),
    ("BKNG", "Booking Holdings Inc.", "Consumer Discretionary", 0.41),
    ("NBIS", "Nebius Group N.V. Class A Ordinary Shares", "Communication Services", 0.41),
    ("HON", "Honeywell International Inc.", "Industrials", 0.40),
    ("ORLY", "O'Reilly Automotive, Inc.", "Consumer Discretionary", 0.39),
    ("ISRG", "Intuitive Surgical, Inc.", "Health Care", 0.39),
    ("WBD", "Warner Bros. Discovery, Inc. Series A", "Communication Services", 0.38),
    ("VRTX", "Vertex Pharmaceuticals Incorporated", "Health Care", 0.37),
    ("MPWR", "Monolithic Power Systems, Inc.", "Technology", 0.37),
    ("PCAR", "PACCAR Inc.", "Industrials", 0.36),
    ("AEP", "American Electric Power Company, Inc.", "Utilities", 0.35),
    ("FTNT", "Fortinet, Inc.", "Technology", 0.35),
    ("TER", "Teradyne, Inc.", "Technology", 0.34),
    ("BKR", "Baker Hughes Company Class A", "Energy", 0.33),
    ("NXPI", "NXP Semiconductors N.V.", "Technology", 0.32),
    ("FAST", "Fastenal Company", "Industrials", 0.31),
    ("CRWV", "CoreWeave, Inc. Class A", "Technology", 0.30),
    ("FANG", "Diamondback Energy, Inc.", "Energy", 0.29),
    ("ALAB", "Astera Labs, Inc.", "Technology", 0.28),
    ("ADSK", "Autodesk, Inc.", "Technology", 0.27),
    ("PYPL", "PayPal Holdings, Inc.", "Technology", 0.26),
    ("HONA", "Honeywell Aerospace Inc.", "Industrials", 0.25),
    ("RKLB", "Rocket Lab Corporation", "Industrials", 0.24),
    ("AXON", "Axon Enterprise, Inc.", "Industrials", 0.23),
    ("XEL", "Xcel Energy Inc.", "Utilities", 0.22),
    ("WDAY", "Workday, Inc. Class A", "Technology", 0.21),
    ("CCEP", "Coca-Cola Europacific Partners plc Ordinary Shares", "Consumer Staples", 0.20),
    ("EXC", "Exelon Corporation", "Utilities", 0.19),
    ("FER", "Ferrovial N.V. Ordinary Shares", "Industrials", 0.18),
    ("TTWO", "Take-Two Interactive Software, Inc.", "Communication Services", 0.17),
    ("TRI", "Thomson Reuters Corporation Common Shares", "Industrials", 0.16),
    ("ODFL", "Old Dominion Freight Line, Inc.", "Industrials", 0.15),
    ("PAYX", "Paychex, Inc.", "Technology", 0.14),
    ("IDXX", "IDEXX Laboratories, Inc.", "Health Care", 0.14),
    ("MCHP", "Microchip Technology Incorporated", "Technology", 0.13),
    ("KDP", "Keurig Dr Pepper Inc.", "Consumer Staples", 0.12),
    ("ROP", "Roper Technologies, Inc.", "Industrials", 0.11),
    ("MSTR", "Strategy Inc Common Stock", "Technology", 0.10),
    ("DXCM", "DexCom, Inc.", "Health Care", 0.09),
    ("GEHC", "GE HealthCare Technologies Inc.", "Health Care", 0.08),
    ("ALNY", "Alnylam Pharmaceuticals, Inc.", "Health Care", 0.07),
    ("CPRT", "Copart, Inc. (DE)", "Industrials", 0.05),
    ("PANW", "Palo Alto Networks, Inc.", "Technology", 0.01),
]

SECTORS = sorted(set(s[2] for s in STOCKS))

LAST_UPDATE = "2026-09-14 23:34:47"
DATA_SOURCE = "Nasdaq + Schwab"